### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by jsnjfz** [astarring/mybatis-generator-gui#10]
直接下载编译后的包运行连接数据库连不上，报错
[ERROR] [15:26:32.842] [JavaFX Application Thread] [] com.zzg.mybatis.generator.controller.MainUIController.openTableColumnCustomizationPage:310 --> null
java.lang.NullPointerException: null
	at com.zzg.mybatis.generator.controller.MainUIController.openTableColumnCustomizationPage(MainUIController.java:306) ~[mybatis-generator-gui.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_05]
	at sun.reflect.misc.Trampoline.invoke(Unknown Source) [na:1.8.0_05]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_05]
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source) [na:1.8.0_05]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source) [jfxrt.jar:na]
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.Node.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.control.Button.fire(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1800(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_05]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.access$300(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication$4$1.run(Unknown Source) [jfxrt.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

**Comment by astarring** [comment]
我没法重现你的问题，在好几个地方都没有出现这个问题。这是一个NullPointerException，应该很好解决。如果你自己可以重现，那么请fix请贡献至我的代码库，谢谢了。

**Comment by astarring** [comment]
关闭问题，如果重现请重新再提issue。
