### ISSUE TITLE
java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver

### ISSUE THREAD

**Issue by longwenzi** [astarring/mybatis-generator-gui#22]
我是在Mac 下 执行了
 “  1. git clone https://github.com/astarring/mybatis-generator-gui
     2. cd mybatis-generator-gui
      3. mvn jfx:jar 
”
然后执行  
1. cd target/jfx/app/ 
2. java -jar mybatis-generator-gui.jar
`
在UI界面 填写连接信息，报了上述错误
查看 lib 下并没有 oracle 的驱动包，放classes 下的驱动包  重启UI ，依然报错

java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_101]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
    at java.lang.Class.forName0(Native Method) ~[na:1.8.0_101]
    at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_101]
    at com.zzg.mybatis.generator.util.DbUtil.getTableNames(DbUtil.java:32) ~[mybatis-generator-gui.jar:na]
    at com.zzg.mybatis.generator.controller.MainUIController.lambda$null$4(MainUIController.java:132) ~[mybatis-generator-gui.jar:na]
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:na]

**Comment by astarring** [comment]
驱动包是要你们自己下载，然后选择你的驱动包所有的位置的。如果你们觉得这个麻烦以后我可以内置驱动包，不过样驱动版本可能会是个问题。

**Comment by longwenzi** [comment]
建议把驱动等配置  和 建立连接放在一块

**Comment by DavidZze** [comment]
将 src/main/resources/lib/ojdbc14.jar拷贝到mybatis-generator-gui.jar同级目录的 lib 目录下，再运行。

**Comment by astarring** [comment]
请在第一个输入框中选择驱动文件的jar路径
