### ISSUE TITLE
IDEA 直接运行，测试连接报错，Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by jgybzx** [astarring/mybatis-generator-gui#333]
百度搜索是mysql-connector-java版本不对，可项目里边没有用到这个，具体应该改哪个依赖的版本呢？
`D:\Software\Develop\JDK8\jdk1.8.0_201\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:56364,suspend=y,server=n -javaagent:C:\Users\Jgybz\AppData\Local\JetBrains\IntelliJIdea2021.3\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\charsets.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\deploy.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\access-bridge-64.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\cldrdata.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\dnsns.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\jaccess.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\jfxrt.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\localedata.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\nashorn.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\sunec.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\sunjce_provider.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\sunmscapi.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\sunpkcs11.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\ext\zipfs.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\javaws.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\jce.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\jfr.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\jfxswt.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\jsse.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\management-agent.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\plugin.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\resources.jar;D:\Software\Develop\JDK8\jdk1.8.0_201\jre\lib\rt.jar;C:\Users\Jgybz\Desktop\mybatis-generator-gui-0.8.4\target\classes;D:\Document\Java\localRepository\org\mybatis\generator\mybatis-generator-core\1.3.5\mybatis-generator-core-1.3.5.jar;D:\Document\Java\localRepository\ch\qos\logback\logback-classic\1.1.2\logback-classic-1.1.2.jar;D:\Document\Java\localRepository\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar;D:\Document\Java\localRepository\ch\qos\logback\logback-core\1.1.2\logback-core-1.1.2.jar;D:\Document\Java\localRepository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;D:\Document\Java\localRepository\commons-io\commons-io\2.5\commons-io-2.5.jar;D:\Document\Java\localRepository\org\xerial\sqlite-jdbc\3.8.11.2\sqlite-jdbc-3.8.11.2.jar;D:\Document\Java\localRepository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;D:\Document\Java\localRepository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\Document\Java\localRepository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;D:\Document\Java\localRepository\com\alibaba\fastjson\1.2.7\fastjson-1.2.7.jar;D:\Document\Java\localRepository\junit\junit\4.12\junit-4.12.jar;D:\Document\Java\localRepository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\Software\Develop\JetBrains\IntelliJ IDEA 2021.3.3\lib\idea_rt.jar" com.zzg.mybatis.generator.MainUI
Connected to the target VM, address: '127.0.0.1:56364', transport: 'socket'
[INFO] [10:49:21.032] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.ConfigHelper.loadGeneratorConfigs:180 --> sql: SELECT * FROM generator_config
C:\Users\Jgybz\Desktop\mybatis-generator-gui-0.8.4\src\main\resources\lib
jarFiles:[Ljava.io.File;@425fa82f
[INFO] [10:50:05.198] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.<clinit>:32 --> load driver class: com.mysql.jdbc.Driver@35b67197
[INFO] [10:50:05.201] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.<clinit>:32 --> load driver class: oracle.jdbc.driver.OracleDriver@64b32d7
[INFO] [10:50:05.204] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.<clinit>:32 --> load driver class: org.postgresql.Driver@5bed2f49
[INFO] [10:50:05.242] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.<clinit>:32 --> load driver class: SQLServerDriver:2
[INFO] [10:50:05.243] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.getConnectionUrlWithSchema:106 --> getConnectionUrlWithSchema, connection url: jdbc:mysql://127.0.0.1:3306/bjidit_pms?useUnicode=true&useSSL=false&characterEncoding=utf8
[ERROR] [10:50:05.398] [JavaFX Application Thread] [] com.zzg.mybatis.generator.controller.DbConnectionController.testConnection:72 --> Unknown system variable 'query_cache_size'
java.sql.SQLException: Unknown system variable 'query_cache_size'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[na:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[na:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[na:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[na:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505) ~[na:na]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3862) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3290) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2299) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[na:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[na:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_201]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[na:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[na:na]
	at com.zzg.mybatis.generator.util.DbUtil.getConnection(DbUtil.java:48) ~[classes/:na]
	at com.zzg.mybatis.generator.controller.DbConnectionController.testConnection(DbConnectionController.java:69) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) [na:1.8.0_201]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) [na:1.8.0_201]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771) [jfxrt.jar:na]
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.Node.fireEvent(Node.java:8411) [jfxrt.jar:na]
	at javafx.scene.control.Button.fire(Button.java:185) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) [jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) [jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_201]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431) [jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
`

**Comment by jgybzx** [comment]
解决了，pom加入mysql-connector-java 依赖就行

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
