### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by HeroBigData** [astarring/mybatis-generator-gui#51]
Caused by: java.lang.AbstractMethodError: com.zzg.mybatis.generator.plugins.DbRemarksCommentGenerator.addModelClassComment(Lorg/mybatis/generator/api/dom/java/TopLevelClass;Lorg/mybatis/generator/api/IntrospectedTable;)V
	at org.mybatis.generator.codegen.mybatis3.model.BaseRecordGenerator.getCompilationUnits(BaseRecordGenerator.java:70)
	at org.mybatis.generator.codegen.mybatis3.IntrospectedTableMyBatis3Impl.getGeneratedJavaFiles(IntrospectedTableMyBatis3Impl.java:233)
	at org.mybatis.generator.config.Context.generateFiles(Context.java:721)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:189)
	at com.zzg.mybatis.generator.bridge.MybatisGeneratorBridge.generate(MybatisGeneratorBridge.java:122)
	at com.zzg.mybatis.generator.controller.MainUIController.generateCode(MainUIController.java:221)
	... 62 more

**Comment by astarring** [comment]
我创建了一个QQ群，加入讨论，群号：613911142
