### ISSUE TITLE
oracle连接错误

### ISSUE THREAD

**Issue by Devilx1** [astarring/mybatis-generator-gui#83]
Oracle("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:thin:@//%s:%s/%s", "ojdbc14.jar"),

**Comment by Devilx1** [comment]
org.mybatis.generator.exception.InvalidConfigurationException: "type" is required in a plugin in context myid
	at org.mybatis.generator.config.Configuration.validate(Configuration.java:99)
	at org.mybatis.generator.api.MyBatisGenerator.<init>(MyBatisGenerator.java:119)
	at com.zzg.mybatis.generator.bridge.MybatisGeneratorBridge.generate(MybatisGeneratorBridge.java:156)
	at com.zzg.mybatis.generator.controller.MainUIController.generateCode(MainUIController.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)

**Comment by astarring** [comment]
fixed
