### ISSUE TITLE
连接错误，什么原因？帐号密码是其它工具都测试OK？

### ISSUE THREAD

**Issue by darren2900** [astarring/mybatis-generator-gui#89]
[ERROR] [21:30:00.434] [JavaFX Application Thread] [] com.zzg.mybatis.generator.controller.MainUIController.lambda$null$5:169 --> null
java.lang.NullPointerException: null
	at com.zzg.mybatis.generator.util.DbUtil.getConnection(DbUtil.java:48) ~[mybatis-generator-gui-0.8.3.jar:na]
	at com.zzg.mybatis.generator.util.DbUtil.getTableNames(DbUtil.java:56) ~[mybatis-generator-gui-0.8.3.jar:na]
	at com.zzg.mybatis.generator.controller.MainUIController.lambda$null$5(MainUIController.java:151) ~[mybatis-generator-gui-0.8.3.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]

**Comment by Lxjazni7** [comment]
一样的问题

**Comment by astarring** [comment]
@Lxjazni7 @darren2900 你们是什么数据库？版本是多少？

**Comment by Lxjazni7** [comment]
@astarring 我是删除项目后重新导入就ok了 不过在osx下idea 运行时 lib下的驱动不会打包进target 会报驱动找不到的异常 我是手动在下面创了文件夹 放了进去就可以了：）

**Comment by zk230** [comment]
@zouzg   load driver error----    数据库版本5.7.21
